# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "MacroScope"
description: "Macroscope: Portefolio de Geoffrey Migault, vous pouvez y voir une sélection de photos ainsi que des dessins."
author:      "Geoffrey Migault"
