# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Coeur de bois"
description: "Coeur de bois: Site de présentation du travail de Vassili Migault, artisan ébéniste, menuisier. Fabrication de meubles et industries connexes de l'ameublement. 24 grand rue 79170 Asnieres-en-poitou "
author:      "Vassili Migault"
