#-------------------------------
# General Site Settings

menu:
- {name: 'Photos', url: 'photo'}
- {name: 'Dessins', url: 'dessin'}
- {name: 'Contact',  url: 'contact'}
- {name: 'A propos', url: 'about'}

#-------------------------------
# Projects Section

projects:
- {name: 'Humains',   url: 'proj-1'}
- {name: 'Paysages',   url: 'proj-2'}
- {name: 'Petites bêtes', url: 'proj-3'}
- {name: 'Paysages Humains',  url: 'proj-4'}
- {name: 'Microscope',  url: 'proj-5'}
- {name: 'Chrysanthèmiste',  url: 'proj-6'}
- {name: 'Arbres',  url: 'proj-7'}
- {name: 'Pyrolyse Club',  url: 'proj-8'}
- {name: 'Léa Renard',  url: 'proj-9'}
- {name: 'Italcementi',  url: 'proj-10'}

#-------------------------------
# Dessins Section

dessins:
- {name: 'Bestiaire',   url: 'dessin-1'}
- {name: 'Voyages',   url: 'dessin-2'}
- {name: 'Villages',   url: 'dessin-3'}
- {name: 'Passages',   url: 'dessin-4'}
- {name: 'Portraits',   url: 'dessin-5'}



#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/migeoffrey'}
- {icon: 'gitlab',    link: 'https://gitlab.com/migeoffrey'}
- {icon: 'envelope',  link: 'mailto:migault@protonmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Macroscope: Portefolio de Geoffrey Migault, vous pouvez y voir une sélection de photos ainsi que des dessins.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
