#-------------------------------
# General Site Settings

menu:
- {name: 'Intérieur', url: 'photo'}
- {name: 'Extérieur', url: 'dessin'}
- {name: 'Contact',  url: 'contact'}
- {name: 'A propos', url: 'about'}

#-------------------------------
# Projects Section

projects:
- {name: 'Ligne courbe',   url: 'proj-1'}

#-------------------------------
# Dessins Section

dessins:
- {name: 'Bestiaire',   url: 'dessin-1'}



#-------------------------------
# Contact Section

social:
- {icon: 'envelope',  link: 'mailto:v.migault@hotmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: ' Coeur de bois: Site de présentation du travail de Vassili Migault, artisan ébéniste, menuisier. Fabrication de meubles et industries connexes de l ameublement. 24 grand rue 79170 Asnieres-en-poitou. '

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
